# Support Vector Machines

We wil implement both hard-margin SVMs and soft-margin SVMs from scratch on a toy dataset. Apart from `NumPy`, we would need to take the help of `SciPy` for solving the quadratic programming problem.

## Hard-Margin SVM

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [6, 6]

In [ ]:
diabetes_dataset=pd.read_csv('/content/diabetes.csv')

In [ ]:
diabetes_dataset.shape



(768, 9)

In [ ]:
diabetes_dataset['Outcome'].value_counts()


0    500
1    268
Name: Outcome, dtype: int64

In [ ]:
X=diabetes_dataset.drop(columns ='Outcome',axis=1)    #axis=1 is to specify column and axis=0 for row 
y=diabetes_dataset['Outcome'] #storing outcome column in sepearate variable

In [ ]:
np.unique(y)
y[y == 0] = -1

<ipython-input-22-1d5673fc0c6a>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y[y == 0] = -1


Converting the notation of 0 to -1.

In [ ]:
np.unique(y)

array([-1,  1])

### Understand the data

$\mathbf{X}$ is a data-matrix of shape $(d, n)$. $\mathbf{y}$ is a vector of labels of size $(n, )$. Specifically, look at the shapes of the arrays involved.

In [ ]:
X = X.T
d, n = X.shape
d, n 
#  just to fee the algo

(8, 768)

### Computing the Dual Objective

We shall follow a step-by-step approach to computing the dual objective function.

#### Step-1

Compute the object $\mathbf{Y}$ that appears in the dual problem.

In [ ]:
Y = np.diag(y)
print(Y.shape) # n x n
print(Y)
print(X.shape)
# putting all the labels in diagonal manner

(768, 768)
[[ 1  0  0 ...  0  0  0]
 [ 0 -1  0 ...  0  0  0]
 [ 0  0  1 ...  0  0  0]
 ...
 [ 0  0  0 ... -1  0  0]
 [ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0 -1]]
(8, 768)


In [ ]:
X.shape, Y.shape

((8, 768), (768, 768))

#### Step-2

Let $\boldsymbol{\alpha}$ be the dual variable. The dual objective is of the form:

$$
f(\boldsymbol{\alpha}) = \boldsymbol{\alpha}^T \mathbf{1} - \cfrac{1}{2} \cdot \boldsymbol{\alpha}^T \mathbf{Q} \boldsymbol{\alpha}
$$



Compute the matrix $\mathbf{Q}$ for this problem.

In [ ]:
Q = Y.T @ X.T @ X @ Y # n x n
Q.shape

(768, 768)

#### Step-3

Since `SciPy`'s optimization routines take the form of minimizing a function, we will recast $f$ as follows:

$$
f(\boldsymbol{\alpha}) =  \cfrac{1}{2} \cdot \boldsymbol{\alpha}^T \mathbf{Q} \boldsymbol{\alpha} - \boldsymbol{\alpha}^T \mathbf{1}
$$

We now have to solve :

$$
\min \limits_{\boldsymbol{\alpha} \geq 0} \quad f(\boldsymbol{\alpha})
$$

Note that $\max$ changes to $\min$ since we changed the sign of the objective function.

In [ ]:
def f(alpha):
    return 0.5 * alpha.T @ Q @ alpha - alpha.sum()

### Optimize

Finally, we have most of the ingredients to solve the dual problem:

$$
\min \limits_{\boldsymbol{\alpha} \geq 0} \quad \cfrac{1}{2} \cdot \boldsymbol{\alpha}^T \mathbf{Q} \boldsymbol{\alpha} - \boldsymbol{\alpha}^T \mathbf{1}
$$

Find the optimal value, $\boldsymbol{\alpha^{*}}$.

In [ ]:
from scipy import optimize
alpha_init = np.zeros(n)
res = optimize.minimize(f, alpha_init, bounds = optimize.Bounds(0, np.inf))
alpha = res.x
alpha

In [ ]:
print(type(alpha))    
# debugging
boolean = [True if i > 0 else False for i in alpha]

<class 'numpy.ndarray'>


In [ ]:
boolean = np.array(boolean)

In [ ]:
np.unique(boolean)

array([ True])

All the data points have been classified as True when we tried to optimise the DUAL PROBLEM.

This concludes that Naive Version of Support Vector cannot classify as the data is NOT LINEARLY SEPARABLE.

Therefore, a kernalized version with a 'Linear Kernel' is used to solve the problem. 